### ISSUE TITLE
Commands to disable/enable reconciliation for a runtime do not work anymore

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/control-plane#1209] opened 2021-12-15 11:03 UTC
**Description**

The commands to exclude/include runtime from scheduling do not seem to work.

**Expected result**

After calling I'd expect state to change to `reconcile_disabled` 
```
kcp rc -c {shoot} disable
```

After calling I'd expect state to change to `reconcile_pending`
```
kcp rc -c {shoot} enable --force
```
**Actual result**

..but the last status shows `ready` as if nothing was changed.

**Comment by pbochynski** [comment] 2021-12-15 11:31
I experienced the problem that after the sequence:
```
kcp rc -c {shoot} disable
kcp rc -c {shoot} enable
```
my cluster was never reconciled again.

**Comment by pPrecel** [comment] 2021-12-21 14:51
This issue occurs because of the regression provided [here](https://github.com/kyma-incubator/reconciler/pull/542) and this ticket is a duplication of [this Issue](https://github.com/kyma-incubator/reconciler/issues/588). The fix was already merged so the problem should not occur but to avoid problems like these again I'm gonna add an integration test.

**Closed** 2022-01-03 11:00 UTC
Labels: bug, area/cli, area/control-plane
