### ISSUE TITLE
X-Forwarded-For / X-Envoy-External-Address Headers not propagated correctly

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-project/control-plane#1490] opened 2022-03-25 11:17 UTC
**Description**

During investigation of https://github.com/kyma-incubator/reconciler/issues/959 we noticed that our Audit Logs stopped working correctly due to us not being able to read out X-Forwarded-For headers anymore. This is apparently a regression as we previously used X-Envoy-External-Address to fetch our IP. I aligned with @veichtj and it seems that we currently do not have support for this from the Istio managed by Kyma. Nevertheless, Apps in the Control Plane will need access to any form of X-Forwarded-For to support correct Audit Logging

**Expected result**

I expect Audit Logs to be writable from any Pod within the control-plane mesh to have access to X-Forwarded-For style headers to write proper Audit Logs

**Actual result**

No XFF Headers are set and can be read from Applications running inside control-plane

**Steps to reproduce**

A detailed deployment for reproduction is available in the linked issue. You will need to have access to an audit log instance or an application that is able to read out XFF headers. This can be replicated, e.g. by sending requests via KCP CLI or any other external application calling the control-plane

**Troubleshooting**

I have discussed with the Istio team on the solution and debugged the issue to verify that the IP headers are missing. The missing IP causes Bad Request (400) responses on the SAP Audit Log Service, so it is easy to spot for us.

**Comment by tobiscr** [comment] 2022-03-31 08:43
Related to #13492

**Comment by tobiscr** [comment] 2022-09-14 07:21
@strekm : any news regarding this Istio limitation: Is it maybe gone with the newer versions?

**Comment by strekm** [comment] 2022-09-21 08:02
@tobiscr @jakobmoellersap we have it on our radar

**Comment by strekm** [comment] 2022-09-21 08:06
closing as duplicate of https://github.com/kyma-project/kyma/issues/13730

**Closed by strekm** 2022-09-21 08:06 UTC
Labels: kind/bug
