### ISSUE TITLE
SKR provision  failed at step Create_LMS_Tenant on Dev

### ISSUE THREAD

**Issue by life0215** [kyma-project/control-plane#123] opened 2020-08-13 05:36 UTC
**Description**

Provisioning SKRs in dev landscape failed  at step Create_LMS_Tenant , please help investigate.

**Expected result**
Provision finish without issue

**Actual result**
Provision failed at step **Create_LMS_Tenant**

**Steps to reproduce**

**Troubleshooting**
```json
{"instanceID":"fdf69278-7559-4952-9b8f-d0bc4e52becd","level":"error","msg":"Process operation failed: FORCE FAILURE","operation":"fdbb3427-affc-4b2c-9a63-4f3c9e27f968","provisioning":"manager","step":"Create_LMS_Tenant","time":"2020-08-13T00:22:04Z"}
```

**Comment by ksputo** [comment] 2020-08-18 10:12
It was a temporary issue caused by a concurrent KEB deployment existing on DEV, in which **Create_LMS_Tenant** was failing on purpose. Then after some testing it was deleted, see this [commit](https://github.com/kyma-project/control-plane/pull/101/commits/0491e97810098f7bda23c225ac9dc0e9b071a0c2). The intention was to simulate cases described [here](https://github.com/kyma-project/control-plane/issues/53). That being said, I am going to close this issue.

**Closed by ksputo** 2020-08-18 10:12 UTC
Labels: bug, priority/critical
