### ISSUE TITLE
Update shoot test fails due to the operation timeout

### ISSUE THREAD

**Issue by franpog859** [kyma-project/control-plane#218] opened 2020-09-23 09:09 UTC
**Description**

`upgrade-shoot` test in the `pre-master-control-plane-gke-provisioner-integration` job fails after the operation timeout

Here is a log example of such failure:

```
time="2020-09-18T07:42:03Z" level=info msg="Asserting operation de167d77-1a2e-4fe9-a52d-7368d0e4eccf is in Succeeded state."
time="2020-09-18T07:42:03Z" level=info msg="Operation message: error: timeout while processing operation"
    operation.go:26:
                Error Trace:    operation.go:26
                                                        operation.go:13
                                                        upgrade_shoot_test.go:81
                Error:          Not equal:
                                expected: "Succeeded"
time="2020-09-18T07:42:03Z" level=info msg="Ensuring the cluster is deprovisioned..." Provider=Azure TestType=upgrade-shoot
                                actual  : "Failed"
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1,2 @@
                                -(gqlschema.OperationState) (len=9) "Succeeded"
                                +(gqlschema.OperationState) (len=6) "Failed"
                Test:           TestShootUpgrade/Azure
```

I found this issue in [this PR](https://github.com/kyma-project/control-plane/pull/202) but as far as I remember it also occurred sometime before that 

**Expected result**

All tests in the `pre-master-control-plane-gke-provisioner-integration`, especially the `upgrade-shoot` test, in this case, don't fail due to timeouts

**Steps to reproduce**

Run `/test pre-master-control-plane-gke-provisioner-integration` comment on your Control Plane PR, find the PROW cluster name in the job's logs, connect to the PROW cluster, look at the Provisioner's test logs running `kubectl logs -n kcp-system oct-tp-testsuite-all-kcp-provisioner-tests-0 tests -f`. After a long long time, the test may fail due to the timeout

**Comment by janmedrek** [comment] 2021-01-07 09:31
Not reproducing since the lib update, closing this one - please feel free to reopen it if it pops up again.

**Closed by janmedrek** 2021-01-07 09:31 UTC
Labels: area/control-plane, test-failing
